name: 'Sonar Yarn Workspaces'
description: 'Create a sonar report per yrn workspace'

inputs:
  root:  # id of input
    description: 'The directory of the package.json containing the workspaces entry, defaults to .'
    required: false
    default: '.'
  args:
    description: Additional arguments to the sonar-scanner
    required: false
branding:
  icon: check
  color: green
runs:
  using: docker
  image: Dockerfile
