
name: Semantic Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  semver:
    runs-on: ubuntu-latest
    #runs-on: []
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - name: Install git
      #   run: apt-get install -y git bash openrc && git --version

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        run: |
          npm install --global yarn && yarn --version
          
      - name: Release
        run: |
          yarn install
          yarn semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: SonarQube
        id: sq
        uses: ./.github/actions/sonar-mono-repo
        env:
          SONAR_TOKEN: "bla"
          SONAR_HOST_URL: "bla"
          SONAR_PROJECT_NAME: "bla"
          SONAR_PROJECTKEY: "bla"
          ROOTDIR: "."
          