
name: Semantic Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  semver:
    runs-on: ubuntu-latest
    #runs-on: []
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - name: Install git
      #   run: apt-get install -y git bash openrc && git --version

      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Install Node
      #   run: |
      #     npm install --global yarn && yarn --version
          
      # - name: Release
      #   run: |
      #     yarn install
      #     yarn semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Yarn build
      #   run: |
      #     yarn install
      #     yarn build

      - name: SonarQube
        id: sq
        uses: ./.github/actions/sonar-mono-repo
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
          SONAR_PROJECT_NAME: ${{secrets.SONAR_PROJECT_NAME}}
          SONAR_PROJECTKEY: ${{secrets.SONAR_PROJECTKEY}}
          SONAR_SOURCE_DIR: ${{secrets.SONAR_SOURCE_DIR}}
          